// Generated by gencpp from file tutorialPKG/AddTwoInts.msg
// DO NOT EDIT!


#ifndef TUTORIALPKG_MESSAGE_ADDTWOINTS_H
#define TUTORIALPKG_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <tutorialPKG/AddTwoIntsRequest.h>
#include <tutorialPKG/AddTwoIntsResponse.h>


namespace tutorialPKG
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace tutorialPKG


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tutorialPKG::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::tutorialPKG::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::tutorialPKG::AddTwoInts > {
  static const char* value()
  {
    return "tutorialPKG/AddTwoInts";
  }

  static const char* value(const ::tutorialPKG::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::tutorialPKG::AddTwoIntsRequest> should match
// service_traits::MD5Sum< ::tutorialPKG::AddTwoInts >
template<>
struct MD5Sum< ::tutorialPKG::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tutorialPKG::AddTwoInts >::value();
  }
  static const char* value(const ::tutorialPKG::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tutorialPKG::AddTwoIntsRequest> should match
// service_traits::DataType< ::tutorialPKG::AddTwoInts >
template<>
struct DataType< ::tutorialPKG::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::tutorialPKG::AddTwoInts >::value();
  }
  static const char* value(const ::tutorialPKG::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tutorialPKG::AddTwoIntsResponse> should match
// service_traits::MD5Sum< ::tutorialPKG::AddTwoInts >
template<>
struct MD5Sum< ::tutorialPKG::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tutorialPKG::AddTwoInts >::value();
  }
  static const char* value(const ::tutorialPKG::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tutorialPKG::AddTwoIntsResponse> should match
// service_traits::DataType< ::tutorialPKG::AddTwoInts >
template<>
struct DataType< ::tutorialPKG::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::tutorialPKG::AddTwoInts >::value();
  }
  static const char* value(const ::tutorialPKG::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TUTORIALPKG_MESSAGE_ADDTWOINTS_H
