// Generated by gencpp from file tutorialPKG/person_data.msg
// DO NOT EDIT!


#ifndef TUTORIALPKG_MESSAGE_PERSON_DATA_H
#define TUTORIALPKG_MESSAGE_PERSON_DATA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tutorialPKG
{
template <class ContainerAllocator>
struct person_data_
{
  typedef person_data_<ContainerAllocator> Type;

  person_data_()
    : name()
    , age(0)
    , color()
    , sum(0)  {
    }
  person_data_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , age(0)
    , color(_alloc)
    , sum(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;

   typedef uint8_t _age_type;
  _age_type age;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _color_type;
  _color_type color;

   typedef int64_t _sum_type;
  _sum_type sum;





  typedef boost::shared_ptr< ::tutorialPKG::person_data_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tutorialPKG::person_data_<ContainerAllocator> const> ConstPtr;

}; // struct person_data_

typedef ::tutorialPKG::person_data_<std::allocator<void> > person_data;

typedef boost::shared_ptr< ::tutorialPKG::person_data > person_dataPtr;
typedef boost::shared_ptr< ::tutorialPKG::person_data const> person_dataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tutorialPKG::person_data_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tutorialPKG::person_data_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tutorialPKG::person_data_<ContainerAllocator1> & lhs, const ::tutorialPKG::person_data_<ContainerAllocator2> & rhs)
{
  return lhs.name == rhs.name &&
    lhs.age == rhs.age &&
    lhs.color == rhs.color &&
    lhs.sum == rhs.sum;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tutorialPKG::person_data_<ContainerAllocator1> & lhs, const ::tutorialPKG::person_data_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tutorialPKG

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::tutorialPKG::person_data_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tutorialPKG::person_data_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tutorialPKG::person_data_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tutorialPKG::person_data_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tutorialPKG::person_data_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tutorialPKG::person_data_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tutorialPKG::person_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7fcf566617780e49c632c8f9e7564d0c";
  }

  static const char* value(const ::tutorialPKG::person_data_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7fcf566617780e49ULL;
  static const uint64_t static_value2 = 0xc632c8f9e7564d0cULL;
};

template<class ContainerAllocator>
struct DataType< ::tutorialPKG::person_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tutorialPKG/person_data";
  }

  static const char* value(const ::tutorialPKG::person_data_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tutorialPKG::person_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string name\n"
"uint8 age\n"
"string color\n"
"int64 sum\n"
;
  }

  static const char* value(const ::tutorialPKG::person_data_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tutorialPKG::person_data_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.age);
      stream.next(m.color);
      stream.next(m.sum);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct person_data_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tutorialPKG::person_data_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tutorialPKG::person_data_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
    s << indent << "age: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.age);
    s << indent << "color: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.color);
    s << indent << "sum: ";
    Printer<int64_t>::stream(s, indent + "  ", v.sum);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TUTORIALPKG_MESSAGE_PERSON_DATA_H
